import type { MessageKey } from "./en";

export const zhCN: Record<MessageKey, string> = {
  "common.language":"语言","common.chinese":"中文","common.english":"EN","common.back":"← 返回全部原型","common.pause":"暂停","common.resume":"继续","common.reset":"重置","common.restart":"重新开始","common.autoRun":"自动运行","common.pauseAuto":"暂停自动运行","common.debugView":"调试视图","common.recommended":"推荐实验","common.whatYouSee":"你看到的是什么","common.coreIdea":"核心思路","common.minimalAlgorithm":"最小算法","common.implementation":"实现方式","common.codeStructure":"代码结构","common.nextExperiments":"后续实验","common.commonAlternatives":"常见替代方案","common.whereUsed":"游戏中的应用","common.parameters":"可调参数","common.agents":"单位","common.speed":"速度",
  "home.eyebrow":"游戏开发游乐场 / 技术图谱","home.copy":"从可观察现象出发，通过算法、可读代码和交互原型探索游戏真正如何运作。","home.search":"搜索水体、Shader、寻路、噪声……","home.surprise":"随机探索","home.explore":"探索技术图谱","home.prototypes":"交互原型","home.empty":"没有匹配的原型。","home.footer":"为最小、真实、易于观察的实验而构建。","home.all":"全部","home.countOne":"1 个实验","home.countMany":"{count} 个实验","home.difficulty":"难度",
  "category.world":"世界与模拟","category.rendering":"渲染","category.physics":"物理","category.ai":"AI","category.gameplay":"玩法","category.procedural":"程序化生成","category.networking":"网络","category.audio":"音频","category.tools":"工具","category.other":"其他","status.prototype":"原型","status.polished":"已打磨",
  "metadata.bouncing.title":"弹跳小球","metadata.bouncing.description":"最小化展示重力、碰撞与恢复系数。","metadata.rope.title":"Verlet 绳索","metadata.rope.description":"探索 Verlet 积分与基于位置的绳索约束。","metadata.flow.title":"流场寻路","metadata.flow.description":"为大量移动单位构建一张共享导航场。","metadata.sdf.title":"SDF 实验场","metadata.sdf.description":"使用有符号距离渲染、融合并查询程序化形状。","metadata.crowd.title":"群体转向实验室","metadata.crowd.description":"组合 Seek 与 Separation，探索群体中的局部移动。","metadata.constraint.title":"约束生成实验室","metadata.constraint.description":"观察 WFC 如何从候选集、最小熵坍缩与约束传播中产生。",
  "constraint.subtitle":"WFC 核心：坍缩（Collapse）+ 传播（Propagation）。","constraint.intro":"生成前的格子并不是空的——它包含多个仍然合法的可能状态。","constraint.collapseStep":"坍缩一步","constraint.propagationStep":"传播一步","constraint.randomSeed":"随机种子","constraint.seed":"种子","constraint.queue":"传播队列","constraint.queueTitle":"等待向外传播变化的格子","constraint.queueHint":"FIFO · 队首优先","constraint.possibilities":"剩余可能性","constraint.showEntropy":"显示熵","constraint.showCandidates":"显示候选集","constraint.current":"当前处理","constraint.changed":"本步变化","constraint.queued":"队列中","constraint.rules":"Tile 兼容规则","constraint.rulesTitle":"有方向的局部规则","constraint.rulesBody":"第一组规则为了清晰采用对称设计，但数据中明确保存了上、右、下、左四个方向的兼容关系。","constraint.experimentTitle":"观察一个决定如何传播","constraint.candidates":"候选集（Candidate Sets）","constraint.candidatesBody":"尚未坍缩的格子并非空白。候选集记录该位置仍然合法的全部 Tile。","constraint.collapse":"坍缩（Collapse）","constraint.collapseBody":"这里的坍缩不是物理坍缩，而是让一个格子从多个可能状态确定为一个状态。","constraint.entropy":"最小熵（Minimum Entropy）","constraint.entropyBody":"V0.1 使用剩余候选数量作为教学用熵，而不是 Shannon Entropy。候选越少，格子受到的约束越强，因此算法优先从最低熵格子中随机选择。该启发式会减少不确定性，但不能保证一定成功。","constraint.propagation":"约束传播（Constraint Propagation）","constraint.propagationBody":"任何候选集变化都可能影响邻居。传播会持续到队列为空，让局部兼容规则逐渐形成整体结构。","constraint.pipeline":"WFC 核心流程","constraint.pipelineBody":"坍缩负责做出局部决定，传播负责让这个决定影响整张网格。","constraint.randomVs":"纯随机与约束生成","constraint.contradiction":"矛盾（Contradiction）","constraint.related":"相关思想","constraint.scope":"范围与后续实验",
  "crowd.subtitle":"为什么大量单位朝同一个目标移动时，不会全部堆成一个点？","crowd.intro":"组合寻目标意图与局部分离行为，并直接观察最终结果。","crowd.hint":"点击空白处移动目标；点击单位查看其局部转向数据。","crowd.maxSpeed":"最大速度","crowd.maxForce":"最大转向力","crowd.seekWeight":"Seek 权重","crowd.separationWeight":"Separation 权重","crowd.neighborRadius":"邻居半径","crowd.separation":"分离行为（Separation）","crowd.coreComparison":"核心对比","crowd.presets":"教学预设","crowd.quick":"快速实验","crowd.seekOnly":"仅 Seek","crowd.balanced":"平衡","crowd.strong":"强分离","crowd.crowded":"拥挤群体","crowd.decompose":"拆解加权转向行为","crowd.showVelocity":"显示速度","crowd.showSeek":"显示 Seek","crowd.showSeparation":"显示 Separation","crowd.showNeighbor":"显示邻居半径","crowd.showFinal":"显示最终转向量","crowd.inspector":"选中单位","crowd.inspectorTitle":"局部转向检查器","crowd.seek":"寻目标（Seek）","crowd.weighted":"加权转向","crowd.notCollision":"Separation 不是碰撞","crowd.pathVs":"寻路与转向行为","crowd.pipeline":"模拟流程","crowd.neighborSearch":"当前邻居搜索",
  "flow.subtitle":"构建一张共享导航场，让数百个单位只查询当前位置的局部方向。","flow.hint":"点击设置目标，或使用 WASD / 方向键移动目标。选择生成单位后，按住并拖动即可连续绘制单位。","flow.showAgents":"显示单位","flow.interaction":"交互模式","flow.pointer":"鼠标当前会修改什么","flow.target":"目标","flow.obstacle":"障碍","flow.erase":"擦除障碍","flow.mud":"泥地","flow.normal":"普通地面","flow.spawn":"生成单位","flow.display":"如何显示 Field 数据","flow.cost":"代价","flow.integration":"积分场","flow.direction":"方向场","flow.costNotSpeed":"代价不等于速度","flow.whenFits":"适用场景","flow.known":"已知限制",
  "sdf.subtitle":"每个像素都在问：“我离最近的形状边界有多远？”拖动圆和方框进行探索。","sdf.circleRadius":"圆半径","sdf.boxWidth":"方框半宽","sdf.boxHeight":"方框半高","sdf.outline":"描边宽度","sdf.glow":"辉光宽度","sdf.softness":"边缘柔和度","sdf.blend":"平滑并集融合","sdf.application":"应用场景","sdf.applicationHint":"同一个距离函数在游戏中的不同含义","sdf.playground":"基础实验","sdf.uiOutline":"UI 描边","sdf.spell":"技能区域","sdf.metaball":"融球效果","sdf.collision":"碰撞探针","sdf.operation":"布尔运算","sdf.circle":"圆","sdf.box":"方框","sdf.union":"并集","sdf.intersection":"交集","sdf.subtract":"相减","sdf.smoothUnion":"平滑并集","sdf.distance":"距离","sdf.sign":"符号","sdf.contour":"等距线","sdf.why":"游戏为何关心 SDF","sdf.oneDistance":"一个距离函数","sdf.circleIntuition":"圆形直觉","sdf.boxIntuition":"方框直觉","sdf.boolean":"布尔运算","sdf.effects":"由距离产生效果","sdf.analytic":"解析 SDF 与纹理 SDF",
  "rope.subtitle":"用一条绳索区分位置预测与基于位置的约束修正。","rope.predicted":"预测位置","rope.notSolved":"约束尚未求解","rope.hint":"拖动绳索后暂停。反复使用求解器步进，观察约束逐轮收敛。","rope.frameStep":"帧步进","rope.solverStep":"求解器步进","rope.reset":"重置绳索","rope.availablePaused":"暂停后可用","rope.gravity":"重力","rope.points":"粒子数","rope.segment":"绳段长度","rope.stepControls":"步进控制","rope.pauseActivate":"暂停以启用两个步进按钮","rope.iterations":"约束迭代次数","rope.errorConvergence":"误差收敛","rope.hidden":"观察隐藏状态","rope.showParticles":"显示粒子","rope.showConstraints":"显示约束","rope.showPrevious":"显示上一位置","rope.showError":"显示约束误差","rope.pipeline":"模拟流程","rope.parts":"各阶段解决什么","rope.verlet":"Verlet 积分","rope.pbd":"基于位置的动力学（PBD）","rope.distanceConstraint":"距离约束","rope.whyIterations":"迭代次数为何重要","rope.run":"运行实验",
  "bounce.gravity":"重力","bounce.showVelocity":"显示速度向量",
  "stats.phase":"阶段","stats.collapsed":"已确定","stats.queue":"队列","stats.collapseDecisions":"坍缩决策","stats.propagationSteps":"传播步骤","stats.cells":"格子","stats.sharedFields":"共享场","stats.rebuilds":"重建次数","stats.separation":"分离行为","stats.avgNeighbors":"平均邻居数","stats.solver":"求解器","stats.avgError":"平均误差","stats.maxError":"最大误差","phase.ready":"就绪","phase.collapsed":"已坍缩","phase.propagating":"传播中","phase.complete":"完成","phase.contradiction":"矛盾","constraint.queueEmpty":"队列为空——下一项生成动作是坍缩。","constraint.phaseReady":"就绪——队列为空，下一项算法动作是选择最小熵格子并坍缩。","constraint.phaseCollapsed":"已坍缩一个最小熵格子，约束尚未传播。","constraint.phasePropagating":"传播中——一个候选集变化可能让更多邻居进入队列。","constraint.phaseComplete":"生成完成——每个格子都只剩一个 Tile。","constraint.phaseFailed":"生成失败——某个格子没有合法候选。V0.1 不进行回溯，请重新开始。","crowd.selectAgent":"选择一个单位以查看其局部转向数据。","sdf.shaderFailed":"Shader 初始化失败","sdf.movePointer":"将鼠标移到画布上。","rope.stepNow":"步进控制现已可用","rope.stepAvailable":"步进控制可用",
  "bounce.body1":"小球每帧获得向下速度。越过地面后，它会被拉回表面，竖直速度反向并损失一部分能量。","bounce.body2":"重力改变速度，速度改变位置；碰撞响应限制位置并改变运动方向。","bounce.body3":"Demo 使用半隐式 Euler 积分并限制过大的帧间隔。恢复系数 0.78 让每次弹跳都会损失能量。","bounce.body4":"提高重力，观察速度箭头更快变长；关闭向量可对比干净画面与调试视图。","bounce.body5":"固定时间步模拟更具确定性；Verlet 积分适合约束，而物理引擎用于复杂形状与接触流形。","bounce.body6":"平台游戏、投射物、粒子以及物理道具都建立在这个循环上。","bounce.body7":"可继续加入空气阻力、可变恢复系数、固定时间步或多球碰撞。",
  "flow.body1":"目标不再让每个单位分别运行 A*，而是构建一张共享 Field。每个单位只需询问：“我当前格子指向哪里？”","flow.body4":"Field 从目标反向构建，一次扩展即可计算所有可达格子的剩余代价，供全部单位共享。普通格进入代价为 1，泥地为 4；直线代价乘 1，对角线乘 √2。","flow.body6":"在路线前绘制泥地，观察群体选择更长但更便宜的路径；擦除后恢复直接路线。Cost 显示 1、4 与 ∞，Integration 显示累计结果。","flow.body7":"泥地只影响寻路偏好。单位不会在泥地减速；惩罚已经预计算进共享 Flow Field。","flow.body8":"当大量单位共享目标时，Flow Field 很有优势。若每个单位目标不同，为每个目标重建整图可能比独立寻路更贵。","flow.body9":"A* 聚焦单条路径；Dijkstra 按代价扩展；NavMesh 处理连续空间；分层 A* 降低大地图搜索量；Steering 处理局部移动。","flow.body10":"RTS 军团、塔防敌人、僵尸群、大型人群与海量敌人 AI。","flow.body11":"V0.1 的单位只跟随格子方向，没有局部碰撞、转向或避障。它们可能重叠；这些是刻意拆开的群体移动问题。",
  "sdf.body1":"SDF 是函数 f(position) → signed distance。Application 决定距离在游戏中的含义；Debug View 展示同一个底层 Field。","sdf.body2":"一份空间距离信息可以同时服务渲染、VFX、UI 与玩法查询。GPU 用它生成像素，CPU 用同样数学执行区域与碰撞查询。","sdf.body4":"形状并非以几何体直接绘制。每个像素计算圆与方框的距离并组合，再转换成填充、描边、辉光或等距线。","sdf.body10":"这里使用解析 SDF：公式实时计算距离。字体渲染常使用纹理 SDF，从图像采样预计算距离。","sdf.body11":"传统几何体、Canvas 路径、纹理遮罩以不同方式绘制形状；MSDF 使用多通道保留文字尖角。",
  "rope.bodyParts":"Verlet 预测粒子位置，PBD 风格求解器再直接修正违反距离、固定点、运动学拖拽或碰撞约束的位置。二者是协作阶段。","rope.bodyPbd":"PBD 不要求先求出精确约束力，而是直接移动位置，使系统逐渐接近合法配置。","rope.bodyDistance":"求解器比较相邻粒子的当前距离与静止长度 L。两个动态粒子平分修正；与固定点或拖拽点相连的粒子承担全部修正。","rope.bodySolver":"暂停后点击 Solver Step。第一次只执行 Verlet 预测；之后每次执行一个 Constraint Pass。历史记录各阶段的真实误差。",
  "crowd.body1":"每个单位都有位置和速度。Seek 让速度朝向目标；Separation 提供远离邻居的方向。二者加权并限制转向力后驱动运动。","crowd.bodySeparation":"邻居半径决定谁能影响本次局部决策。V0.1 直接检查每一对单位。","crowd.bodyWeighted":"权重表达互相竞争的移动目标，最大转向力限制速度改变得有多突然。","crowd.bodyNeighbor":"10–150 个单位时刻意使用 O(N²) 搜索，以保持 Steering 规则清晰。Spatial Hash、Quadtree 与 BVH 值得单独实验。"
};
